# Add AMIS DB url (11/18/2016)
#db.url=jdbc:oracle:thin:@172.26.56.110:1521:aami
#db.user=aami
#db.password=jBAkNzyitcDRTFwG4amUmrwYkIpyGswj

db.user = aami
db.password = e7Jo9+7KjvsuU8MQs3kDqgzAF7LgS8LF
db.url = jdbc:oracle:thin:@10.2.10.8:1521:aami

db.workspace=AMIS
db.workspace_old_aami=AAMI
db.workspace_predict=AAMI

localtest.db.url=jdbc:oracle:thin:@172.26.56.110:1521:aami
localtest.db.user=aami
localtest.db.password=jBAkNzyitcDRTFwG4amUmrwYkIpyGswj
localtest.db.workspace=AMIS
localtest.db.workspace_old_aami=AAMI
localtest.db.workspace_predict=AAMI

db.amis.url=jdbc:oracle:thin:@190.1.61.15:1523/sidamis
db.amis.user=fly
db.amis.password=2CqMBEKV6hNypkYo3UgaIaWn2O3sh1eN

localtest.db.amis.url=jdbc:oracle:thin:@190.1.61.15:1523/sidamis
localtest.db.amis.user=fly
localtest.db.amis.password=2CqMBEKV6hNypkYo3UgaIaWn2O3sh1eN

global.ftpPath.unix=/data/ftp/virtual/skamet
global.ftpPath.windows=F:/data/ftp

global.storePath.unix=/data/DATA_STORE
global.storePath.windows=F:/data/datastore

global.comisPath.unix=/data1/COMIS_DATA

# \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\u4e2e (global.storePath + "Temp")
global.corruptedFileDirName=temp

#global.progRoot=/data/batch/dmon/JAVA/KAMA_DAEMON
global.progRoot=C:/Users/User/git/skamet-daemon/KAMA_DAEMON
 			
buoy.filter=VBKO60_[0-9]{10}|VBKO60_[0-9]{12}][0-9]{5}
buoy.path=${global.storePath}/BUOY
buoy.type=BUOY

asos.filter=SHKO60_[0-9]{12}
asos.path=${global.storePath}/ASOS
asos.type=ASOS

lau.filter=LAU_[0-9]{1,4}_[0-9]{16}.bin
lau.path=${global.storePath}/LAU
lau.type=LAU

#Device Setting
amos.filter=AMOS_MIN_[0-9]{1,3}_[0-9]{14}.txt
amos.path=${global.storePath}/AMOS
amos.type=AMOS

aws.filter=AWS_MIN_[0-9]{12}
aws.path=${global.storePath}/AWS
aws.type=AWS

amdar.filter=(AAMDAR|KAMDAR)_[0-9]{12}(.+).txt
amdar.path=${global.storePath}/AMDAR
amdar.type=AMDAR

#lgt.filter=LGT_KMA_[0-9]{12}.asc
lgt.filter=KMA_LGT_NX1_[0-9]{12}.asc
lgt.path=${global.storePath}/LGT
lgt.type=LGT

wpf.filter=WPF_DATA_MIN_[A-Z]{4}_[0-9]{14}.txt
wpf.path=${global.storePath}/WPF
wpf.type=WPF

lwpu.filter=LWPU_[0-9]{5}_[0-9]{12}.DAT
lwpu.path=${global.storePath}/LWPU
lwpu.type=LWPU

hwpu.filter=HWPU_[0-9]{5}_[0-9]{12}.DAT
hwpu.path=${global.storePath}/HWPU
hwpu.type=HWPU

coms.filter=coms(.+).png
coms.path=${global.storePath}/Coms
coms.type=coms

hiway.filter=hiway_min_[0-9]{12}
hiway.path=${global.storePath}/Mor_hiway_min
hiway.type=hiway

cnqcz.filter=RDR_CNQCZ_[A-Z0-9]{4}_[0-9]{12}.bin.gz
cnqcz.path=${global.storePath}/RDR
cnqcz.type=CNQCZ

coqvr.filter=RDR_COQVR_[A-Z]{3}_[0-9]{12}.dat.gz
coqvr.path=${global.storePath}/RDR
coqvr.type=COQVR

inchonvts.filter=inchonvts_[0-9]{3}_[0-9]{8}.csv
inchonvts.path=${global.storePath}/inchonvts
inchonvts.type=inchonvts

navy.filter=NAVY_[0-9]{10}_[0-9]{4}
navy.path=${global.storePath}/NAVY
navy.type=NAVY

sako82.filter=SAKO82_[A-Z]{4}_[0-9]{12}_[0-9]{3}I
sako82.path=${global.storePath}/Metar
sako82.type=SAKO82

road.filter=road_min_[0-9]{12}
road.path=${global.storePath}/Road
road.type=road

upp.filter=UPP_RAW_[0-9]{5}_[0-9]{14}.txt
upp.path=${global.storePath}/UPP
upp.type=UPP

cfqcz.filter=RDR_CFQCZ_[A-Z0-9]{4}_[0-9]{12}.bin.gz
cfqcz.path=${global.storePath}/RDR
cfqcz.type=CFQCZ

# Prediction models (12/29/2016)
ukmo.filter=usst_raw.[0-9]{10}.gdat
ukmo.path=${global.storePath}/UKMO
ukmo.type=UKMO

ldaps_sgl.filter=(ldps_l1p5_ufog.[0-9]{10}_[0-9]{3}|ldps_l1p5_fk4s.[0-9]{10}_[0-9]{3}-[0-9]{3}|ldps_lc06_grph.[0-9]{10}_[0-9]{3}|lfog_visb.[0-9]{10}_[0-9]{3})
ldaps_sgl.path=${global.storePath}/LDAPS_SGL
ldaps_sgl.type=LDAPS_SGL

# 2017/01/10 \ufffd\u07f0\ufffd (2\ufffd\ufffd)
awos.filter=AWOS_MIN_AAF_[0-9]{12}.txt
awos.path=${global.storePath}/AWOS
awos.type=AWOS

sako.filter=SAKO_ARMY_[0-9]{12}_[0-9]{4}
sako.path=${global.storePath}/SAKO
sako.type=SAKO

# 2017/01/16 \ufffd\u07f0\ufffd (\ufffd\ufffd\ufffd\ufffd\ufffd)
ldaps_isob.filter=ldps_city_grph_[0-9]{10}.dat
ldaps_isob.path=${global.storePath}/LDAPS_ISOB
ldaps_isob.type=LDAPS_ISOB

# 2017/01/23 \ufffd\u07f0\ufffd (\ufffd\ufffd\ufffd\ufffd\ufffd)
lfog.filter=(lfog_vis_[0-9]{12}.asc|lfog_out.[0-9]{4}.[0-9]{10}.bin)
lfog.path=${global.storePath}/LFOG
lfog.type=LFOG

rfog.filter=(rfog_vis_[0-9]{12}.asc|rfog_out.[0-9]{4}.[0-9]{10}.bin)
rfog.path=${global.storePath}/RFOG
rfog.type=RFOG

# 2017/01/24 \ufffd\u07f0\ufffd (\ufffd\ufffd\ufffd\ufffd\ufffd)
#wafc.filter=([0-9]{8}_[0-9]{4}f[0-9]{2}.grib2|[0-9]{8}_[0-9]{4}f[0-9]{2}.grib2.ncx3|[0-9]{8}_[0-9]{4}f[0-9]{2}.grib2.gbx9)
wafc.filter=[0-9]{8}_[0-9]{4}f[0-9]{2}.grib2
wafc.path=${global.storePath}/WAFC
wafc.type=WAFC

#ktg.filter=air_tub[12]{1}_umrg_h[0-9]{2}\\.[0-9]{10}.nc
ktg.filter=amo_gdum_ktgm_(midl|uppl)_f[0-9]{2}_[0-9]{10}.nc
ktg.path=${global.storePath}/KTG
ktg.type=KTG
ktg.coordinates.lat.path=${global.progRoot}/res/ktg_lat.bin
ktg.coordinates.lon.path=${global.progRoot}/res/ktg_lon.bin

kim_ktg.filter=amo_gdps_ktgm_(midl|uppl)_f[0-9]{2}_[0-9]{10}.nc
kim_ktg.path=${global.storePath}/KIM_KTG
kim_ktg.type=KIM_KTG
kim_ktg.coordinates.lat.path=${global.progRoot}/res/kim_ktg_lat.bin
kim_ktg.coordinates.lon.path=${global.progRoot}/res/kim_ktg_lon.bin

ktg_diag_indx.filter=amo_gdum_ktgm_(midl|uppl)_indx_f[0-9]{2}_[0-9]{10}.nc
ktg_diag_indx.path=${global.storePath}/KTG_DIAG_INDX
ktg_diag_indx.type=KTG_DIAG_INDX
ktg_diag_indx.coordinates.lat.path=${global.progRoot}/res/ktg_lat.bin
ktg_diag_indx.coordinates.lon.path=${global.progRoot}/res/ktg_lon.bin

# RDAPS \ufffd\u07f0\ufffd (\ufffd\u04fd\u00f1\ufffd\ufffd\ufffd)
rdaps_sgl.filter=(r120_asia_grph_[0-9]{10}_[0-9]{3}.dat|r120_fxko_grph_[0-9]{10}.dat|r120_ufog_lc10_grph.[0-9]{10})|rfog_visb.[0-9]{10}_[0-9]{3}
rdaps_sgl.path=${global.storePath}/RDAPS_SGL
rdaps_sgl.type=RDAPS_SGL

rdaps_isob.filter=r120_city_grph_korea.[0-9]{10}
rdaps_isob.path=${global.storePath}/RDAPS_ISOB
rdaps_isob.type=RDAPS_ISOB

# AIREP (\ufffd\ufffd\ufffd\ufffd\ufffd)
airep.filter=AIREP_RKSI_[0-9]{14}
airep.path=${global.storePath}/AIREP
airep.type=AIREP

# 3D \ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd; 2017/02/15 \ufffd\u07f0\ufffd (um_loa, rea, vis)
um_loa.filter=qwumloa_pb[0-9]{3}.nc.tgz
um_loa.path=${global.storePath}/UM_LOA
um_loa.type=UM_LOA
um_loa.coordinates.lat.path=${global.progRoot}/res/ldps_lat.bin
um_loa.coordinates.lon.path=${global.progRoot}/res/ldps_lon.bin
um_loa_regrid.coordinates.lat.path=${global.progRoot}/res/ldps_regrid_lat.bin
um_loa_regrid.coordinates.lon.path=${global.progRoot}/res/ldps_regrid_lon.bin

um_loa_pc.filter=qwumloa_pc[0-9]{3}.nc.tgz
um_loa_pc.path=${global.storePath}/UM_LOA_PC
um_loa_pc.type=UM_LOA_PC

um_rea.filter=qwumrea_pb[0-9]{3}.nc.tgz
um_rea.path=${global.storePath}/UM_REA
um_rea.type=UM_REA
 
um_gla.filter=umglaa_pb[0-9]{3}.nc.tgz
um_gla.path=${global.storePath}/UM_GLA
um_gla.type=UM_GLA

um_vis.filter=visibility.nc
um_vis.path=${global.storePath}/UM_VIS
um_vis.type=UM_VIS

# \ufffd\ufffd\ufffd\u05ff\ufffd\ufffd\ufffd
dfs.filter=DFS_SHRT_GRD_GRB3_[A-Z0-9]{3}.[0-9]{12}
dfs.path=${global.storePath}/DFS
dfs.type=DFS

# RISK MATRIX
risk_matrix.filter=[A-Za-z]{4,8}(_WD)*_Risk_Matrix_[A-Za-z]{3,4}[\_0-9]*_[0-9]{10}.png
risk_matrix.path=${global.storePath}/RISK_MATRIX
risk_matrix.type=RISK_MATRIX

risk_matrix_grid.filter=Airport_feet_(spd|wdr)_(sfc|upr)-upr_mem_[0-9]{2}_[0-9]{8}_(00|12).txt
risk_matrix_grid.path=${global.storePath}/RISK_MATRIX
risk_matrix_grid.type=RISK_MATRIX_GRID

# ICING
icing.filter=ICING_UMLG_(8D2|RAP)_[0-9]{10}_f[0-9]{2}_FL[0-9]{2,3}_(KR|EA).gif
icing.path=${global.storePath}/ICING
icing.type=ICING

#GKTG
#gktg.filter=GKTG_(MAX|CAT|MWT)_[0-9]{8}_i[0-9]{2}f[0-9]{2}.nc
gktg.filter=amo_gdum_gktg_(cat|max|mwt)_f[0-9]{2}_[0-9]{10}.nc
gktg.path=${global.storePath}/GKTG
gktg.type=GKTG
gktg.coordinates.lat.path=${global.progRoot}/res/gdps_lat.bin
gktg.coordinates.lon.path=${global.progRoot}/res/gdps_lon.bin

gktg_arcv.filter=amo_gdum_gktg_f[0-9]{2}_[0-9]{10}_arcv.nc
gktg_arcv.path=${global.storePath}/GKTG_ARCV
gktg_arcv.type=GKTG_ARCV
gktg_arcv.coordinates.lat.path=${global.progRoot}/res/gktg_arcv_lat.bin
gktg_arcv.coordinates.lon.path=${global.progRoot}/res/gktg_arcv_lon.bin

#KIM_GKTG
kim_gktg.filter=amo_gdps_gktg_(cat|max|mwt)_f[0-9]{2}_[0-9]{10}.nc
kim_gktg.path=${global.storePath}/KIM_GKTG
kim_gktg.type=KIM_GKTG
kim_gktg.coordinates.lat.path=${global.progRoot}/res/kim_gktg_lat.bin
kim_gktg.coordinates.lon.path=${global.progRoot}/res/kim_gktg_lon.bin

#LDPS_SIGWX
ldps_sigwx.filter=LDPS_[0-9]{10}.nc
ldps_sigwx.path=${global.storePath}/LDPS_SIGWX
ldps_sigwx.type=LDPS_SIGWX

#GDPS_SIGWX
gdps_sigwx.filter=GDPS_[0-9]{10}.nc
gdps_sigwx.path=${global.storePath}/GDPS_SIGWX
gdps_sigwx.type=GDPS_SIGWX

#ECMW_SIGWX
ecmw_sigwx.filter=ECMW_[0-9]{10}.nc
ecmw_sigwx.path=${global.storePath}/GDPS_SIGWX
ecmw_sigwx.type=ECMW_SIGWX

#RKIM_SIGWX:
rkim_sigwx.filter=RKIM_[0-9]{10}.nc
rkim_sigwx.path=${global.storePath}/RKIM_SIGWX
rkim_sigwx.type=RKIM_SIGWX

weathermap.filter=_gdps(.+)([0-9]{10}).(gif|png)
weathermap.path=${global.storePath}/WEATHER_MAP
weathermap.type=WEATHER_MAP

ieodo.filter=ieodo_[0-9]{8}.dat
ieodo.path=${global.storePath}/IEODO
ieodo.type=IEODO

kma_hci.filter=RDR_R3D_KMA_HCI_([0-9]{12}).bin.gz
kma_hci.path=${global.storePath}/RDR
kma_hci.type=KMA_HCI

kma_hail.filter=RDR_CMP_HAIL_EXT_([0-9]{12}).bin.gz
kma_hail.path=${global.storePath}/RDR
kma_hail.type=KMA_HAIL

kma_maple.filter=qpf_ram_10m_maple_([0-9]{12}).bin.gz
kma_maple.path=${global.storePath}/RDR
kma_maple.type=KMA_MAPLE

kma_motion.filter=qpf_ram_10m_kma_([0-9]{12}).bin.gz
kma_motion.path=${global.storePath}/RDR
kma_motion.type=KMA_MOTION

kma_wd.filter=RDR_R3D_KMA_WD_([0-9]{12}).(bin.gz|nc)
kma_wd.path=${global.storePath}/RDR
kma_wd.type=KMA_WD

kma_hsr.filter=RDR_CMP_HSP_PUB_([0-9]{12}).bin.gz
kma_hsr.path=${global.storePath}/RDR
kma_hsr.type=KMA_HSR

rtko66.filter=RTKO66_[0-9]{12}][0-9]+.txt
rtko66.path=${global.storePath}/RTKO66
rtko66.type=RTKO66

rtko63.filter=RTKO63_[0-9]{12}][0-9]+
rtko63.path=${global.storePath}/RTKO63
rtko63.type=RTKO63

dwind.filter=kmapp_(.+)_(surf|vert)_[0-9]{10}_[0-9]{3}.nc
dwind.path=${global.storePath}/DWIND
dwind.type=DWIND
dwind.coordinates.lat.path=${global.progRoot}/res/kmapp_staCode_lat.bin
dwind.coordinates.lon.path=${global.progRoot}/res/kmapp_staCode_lon.bin

kim_dwind.filter=amo_ldps_kldw_(.+)_f[0-9]{2}_[0-9]{10}.nc
kim_dwind.path=${global.storePath}/KIM_DWIND
kim_dwind.type=KIM_DWIND

icing_ea.filter=air_ice0_umrg_h[0-9]{2}.[0-9]{10}.nc
icing_ea.path=${global.storePath}/ICING_EA
icing_ea.type=ICING_EA
icing_ea.coordinates.lat.path=${global.progRoot}/res/icing_ea_lat.bin
icing_ea.coordinates.lon.path=${global.progRoot}/res/icing_ea_lon.bin

icing_kp.filter=air_ice0_umlg_h[0-9]{2}.[0-9]{10}.nc
icing_kp.path=${global.storePath}/ICING_KP
icing_kp.type=ICING_KP
icing_kp.coordinates.lat.path=${global.progRoot}/res/icing_kp_lat.bin
icing_kp.coordinates.lon.path=${global.progRoot}/res/icing_kp_lon.bin

mos.filter=DFS_SHRT_STN_BEST_MERG_T1H_AIR.[0-9]{12}.csv
mos.path=${global.storePath}/MOS
mos.type=MOS

shear_isob.filter=[0-9]{2}[D|A]{1}_shear_[0-9]{10}.F[0-9]{2}.txt
shear_isob.path=${global.storePath}/SHEAR
shear_isob.type=SHEAR_ISOB

shear_sgl.filter=[0-9]{10}_data.txt
shear_sgl.path=${global.storePath}/SHEAR
shear_sgl.type=SHEAR_SGL

shear_lens.filter=lens_llws_enprob_f[0-9]{3}_[0-9]{10}.nc
shear_lens.path=${global.storePath}/SHEAR
shear_lens.type=SHEAR_LENS

shear_img.filter=WindShear_(.+)_[0-9]{10}.png
shear_img.path=${global.storePath}/SHEAR_IMG
shear_img.type=SHEAR_IMG

fois_local.filter=FOISLocalAirportFltInfo_[0-9]{14}.[0-9]{3}.txt
fois_local.path=${global.storePath}/FOISLocalAirport
fois_local.type=FOIS_LOCAL

aoms_incheon.filter=AOMSFltGenInfo_[0-9]{14}.[0-9]{3}.txt
aoms_incheon.path=${global.storePath}/AOMSIncheonAirport
aoms_incheon.type=AOMS_INCHEON

ala_meteo_img.filter=ldps_airport_[0-9]{3}_[0-9]{10}.png
ala_meteo_img.path=${global.storePath}/ALA_METEO_IMG
ala_meteo_img.type=ALA_METEO_IMG

takeoff_klaps.filter=klaps_airport_[0-9]{3}_[0-9]{10}.csv
takeoff_klaps.path=${global.storePath}/TAKEOFF_KLAPS
takeoff_klaps.type=TAKEOFF_KLAPS

seavis_img.filter=SEAVIS_IMG_[0-9]{12}_(.+).jpg
seavis_img.path=${global.storePath}/SEAVIS_IMG
seavis_img.type=SEAVIS_IMG

seavis.filter=SEAVIS_[0-9]{12}_(.+).txt
seavis.path=${global.storePath}/SEAVIS
seavis.type=SEAVIS

kim_gdps.filter=kim_g128_ne36_pres_h[0-9]{3}.[0-9]{10}.gb2
kim_gdps.path=${global.storePath}/KIM_GDPS
kim_gdps.type=KIM_GDPS
kim_gdps.coordinates.lat.path=${global.progRoot}/res/kim_gdps_lat.bin
kim_gdps.coordinates.lon.path=${global.progRoot}/res/kim_gdps_lon.bin

kim_rdps.filter=r030_v040_ne36_pres_h[0-9]{3}.[0-9]{10}.gb2
kim_rdps.path=${global.storePath}/KIM_RDPS
kim_rdps.type=KIM_RDPS
kim_rdps.coordinates.lat.path=${global.progRoot}/res/kim_rdps_lat.bin
kim_rdps.coordinates.lon.path=${global.progRoot}/res/kim_rdps_lon.bin

kim_rdps_unis.filter=r030_v040_ne36_unis_h[0-9]{3}.[0-9]{10}.gb2
kim_rdps_unis.path=${global.storePath}/KIM_RDPS_UNIS
kim_rdps_unis.type=KIM_RDPS_UNIS
kim_rdps_unis.coordinates.lat.path=${global.progRoot}/res/kim_rdps_lat.bin
kim_rdps_unis.coordinates.lon.path=${global.progRoot}/res/kim_rdps_lon.bin

ecmwf.filter=e025_v025_nhem_h[0-9]{3}.[0-9]{12}.nc
ecmwf.path=${global.storePath}/ECMWF
ecmwf.type=ECMWF
ecmwf.coordinates.lat.path=${global.progRoot}/res/ecmwf_lat.bin
ecmwf.coordinates.lon.path=${global.progRoot}/res/ecmwf_lon.bin

nc_to_amo.filter=NC2AMO_AWI_[0-9]{10}.json
nc_to_amo.path=${global.storePath}/NC_TO_AMO
nc_to_amo.type=NC_TO_AMO

fct_klaps_10m.filter=klaps2_airport_[0-9]{3}.[0-9]{12}.csv
fct_klaps_10m.path=${global.storePath}/FCT_KLAPS2
fct_klaps_10m.type=FCT_KLAPS_10M

fct_klaps_1h.filter=klaps2_airport_[0-9]{3}_[0-9]{10}.csv
fct_klaps_1h.path=${global.storePath}/FCT_KLAPS2
fct_klaps_1h.type=FCT_KLAPS_1H

igtcht_img.filter=amo_adm3_vis3_plot.[0-9]{10}.tgz|amo_ecmw_eccl_plot.[0-9]{10}.tgz|amo_ecmw_ufog_plot.[0-9]{10}.tgz|amo_gdum_acim_plot.[0-9]{10}.tgz|amo_gdum_ufog_plot.[0-9]{10}.tgz|amo_gdum_sfip_plot.[0-9]{10}.tgz
igtcht_img.path=${global.storePath}/IGTCHT_IMG
igtcht_img.type=IGTCHT_IMG

low_info_dfs.filter=low_info_dfs_[0-9]{10}.png
low_info_dfs.path=${global.storePath}/LOW_INFO_DFS
low_info_dfs.type=LOW_INFO_DFS

mos_hr01.filter=DFS_SHRT_STN_BEST_MERG_HR01_AIR.[0-9]{12}.csv
mos_hr01.path=${global.storePath}/MOS_HR01
mos_hr01.type=MOS_HR01

ldps_pres.filter=ldps_[0-9]{3}_airport_[0-9]{3}_[0-9]{10}.csv
ldps_pres.path=${global.storePath}/LDPS_PRES
ldps_pres.type=LDPS_PRES

rdps_ne36.filter=rdps_ne36_[0-9]{3,4}.0hPa_[0-9]{3}_[0-9]{10}.csv
rdps_ne36.path=${global.storePath}/RDPS_NE36
rdps_ne36.type=RDPS_NE36

gk2a_img.filter=gk2a_(.+)[0-9]{12}(.*).png
gk2a_img.path=${global.storePath}/SAT
gk2a_img.type=GK2A_IMG

rdr_ext.filter=RDR_R3D_EXT_CZ_(.+).nc|RDR_R3D_EXT_DR_(.+).nc|RDR_R3D_EXT_RH_(.+).nc|RDR_R3D_EXT_HCI_(.+).nc|RDR_OBS_ta_D3D_(.+).nc|RDR_OBS_td_D3D_(.+).nc
rdr_ext.path=${global.storePath}/RDR
rdr_ext.type=RDR_EXT

lgt_ext_wwlln.filter=LGT_EXT_WWLLN_[0-9]{12}.txt
lgt_ext_wwlln.path=${global.storePath}/LGT_EXT_WWLLN
lgt_ext_wwlln.type=LGT_EXT_WWLLN

tof_ensb2.filter=tof_ensb2_[0-9]{10}_[A-Z]{4}.csv
tof_ensb2.path=${global.storePath}/TOF_ENSB2
tof_ensb2.type=TOF_ENSB2

hobs.filter=NAM_ANAL_HOBS_[A-Z]{4}_[0-9]{12}.nc
hobs.path=${global.storePath}/HOBS
hobs.type=HOBS
hobs.coordinates.lat.path=${global.progRoot}/res/hobs_stnCd_lat.bin
hobs.coordinates.lon.path=${global.progRoot}/res/hobs_stnCd_lon.bin

kim_acim_cnvt.filter=amo_gdps_acim_cnvt_f[0-9]{2}_[0-9]{10}.nc
kim_acim_cnvt.path=${global.storePath}/KIM_ACIM_CNVT
kim_acim_cnvt.type=KIM_ACIM_CNVT

vwsh.filter=amo_(.+)vwsh(.+)|NAM_ANAL_RADR_WISD_VWSH(.+).png
vwsh.path=${global.storePath}/VWSH
vwsh.type=VWSH

hwsh.filter=amo_(.+)hwsh(.+)|NAM_ANAL_RADR_WISD_HWSH(.+).png
hwsh.path=${global.storePath}/HWSH
hwsh.type=HWSH

kim_kfip.filter=amo_gdps_kfip_(.+)_f[0-9]{2}_[0-9]{10}.(nc|png)
kim_kfip.path=${global.storePath}/KIM_KFIP
kim_kfip.type=KIM_KFIP
kim_kfip.coordinates.lat.path=${global.progRoot}/res/kim_kfip_lat.bin
kim_kfip.coordinates.lon.path=${global.progRoot}/res/kim_kfip_lon.bin

loow.filter=kim_rdps_(.+)_wndgst_s[0-9]{3}_[0-9]{10}.png
loow.path=${global.storePath}/LOOW
loow.type=LOOW

kima.filter=amo_kima_rkpc_(.+).png
kima.path=${global.storePath}/KIMA
kima.type=KIMA
